### ISSUE TITLE
Starting player causes computer to freeze.

### ISSUE THREAD

**Issue by bluejumper22222** [shane-mason/FieldStation42#357]
When I first started the player, I was able to run the player, and exit the program using the keyboard. Now I am unable to exit the program, and it displays the text: Drop files her or drop url here. I do have files in my station1 folder under necessary folders.

Thank you for any help. :)

**Comment by shane-mason** [comment]
The `Drop files here` display is the default MPV - this happens when its opened but the player has an error or can't find the file. To figure out what's going on, you'll need to look at the output and tell us what you see there. There should be some sort of error being displayed in the terminal behind the MPV window. Just start the player from the command line and then after it dies, copy the text there and post it here.

If its locking up so you can't do anything with the computer, open another terminal (you might have to use ssh to connect your machine, but that is a necessity anyway really) but then issue the command `killall MPV` and it will close that window and you can have control of the computer again.

**Comment by shane-mason** [comment]
Anything else on this one or did you get it worked out?

**Comment by shane-mason** [comment]
I just committed some fixes that might resolve whatever issue you were seeing. Please do `git pull` to get the updates, then delete your db and try again. 
```
rm runtime/fs42_fluid.db
python3 station_42.py -r
```
And it should work for you now.

**Comment by ddrfr33k** [comment]
I'm running into this issue now after updating my Field Station and restarting. Guide is black, and I cannot change channels. I deleted the Fluid DB, then attempted the rebuild. I get the followeing message:

```
Traceback (most recent call last):
  File "/home/station/FieldStation42/station_42.py", line 14, in <module>
    from fs42.fs42_server.fs42_server import mount_fs42_api
  File "/home/station/FieldStation42/fs42/fs42_server/fs42_server.py", line 4, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
```
I did try pulling another update since you announced the fix, and this did not resolve the issue.

**Comment by ddrfr33k** [comment]
I launched Field Player one more time, to get you more details. The Player launches, I hear the guide music, but I don't see anything on screen. When I change the channel, I see "----" on the front mounted LCD display, but it doesn't change.

```
2025-08-10 16:21:42,840 INFO:root:Loading and checking guide channel
2025-08-10 16:21:42,841 INFO:root:Guide channel checks completed.
2025-08-10 16:21:42,843 INFO:MainLoop:Starting main loop
2025-08-10 16:21:42,844 INFO:FieldPlayer:Starting MPV instance
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/station/FieldStation42/field_player.py", line 234, in start_api_server_with_shutdown_queue
    from fs42.fs42_server import fs42_server
  File "/home/station/FieldStation42/fs42/fs42_server/fs42_server.py", line 4, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'
2025-08-10 16:21:43,086 INFO:MainLoop:Playing station: Guide
2025-08-10 16:21:43,086 INFO:MainLoop:Starting the guide channel
2025-08-10 16:21:43,090 INFO:FieldPlayer:playing runtime/guide/background.mp3
2025-08-10 16:21:43,105 INFO:FieldPlayer:## Set duration, returning true
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/station/FieldStation42/fs42/guide_tk.py", line 352, in guide_channel_runner
    ScheduleFrame(app, app.get_conf())
  File "/home/station/FieldStation42/fs42/guide_tk.py", line 160, in __init__
    self.populate_frame()
  File "/home/station/FieldStation42/fs42/guide_tk.py", line 166, in populate_frame
    view = gb.build_view(normalize=self.conf.normalize_title)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/station/FieldStation42/fs42/guide_builder.py", line 97, in build_view
    entries = ScheduleQuery.query_slot(station["network_name"], start_time, normalize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/station/FieldStation42/fs42/guide_builder.py", line 41, in query_slot
    programming_block: LiquidBlock = LiquidManager().get_programming_block(network_name, current_marker)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/station/FieldStation42/fs42/liquid_manager.py", line 154, in get_programming_block
    raise ScheduleNotFound(f"Schedule doesn't exist for {network_name}")
fs42.liquid_manager.ScheduleNotFound: Schedule doesn't exist for KidzTV
2025-08-10 16:21:52,676 INFO:FieldPlayer:Sending the guide channel shutdown command
2025-08-10 16:21:52,677 ERROR:MainLoop:object of type 'int' has no len()
Traceback (most recent call last):
  File "/home/station/FieldStation42/field_player.py", line 175, in main_loop
    channel_index = channel_index if channel_index > 0 else len(channel_index)
                                                            ^^^^^^^^^^^^^^^^^^
TypeError: object of type 'int' has no len()
2025-08-10 16:21:52,678 WARNING:MainLoop:Got payload on channel change, but JSON convert failed
Applying short change effect.
2025-08-10 16:21:52,679 INFO:MainLoop:Playing station: MTV
2025-08-10 16:21:52,679 INFO:MainLoop:Starting station MTV at: sunday 16 skipping=1312 
2025-08-10 16:21:52,681 CRITICAL:FieldPlayer:*********************Schedule Panic*********************
2025-08-10 16:21:52,681 CRITICAL:FieldPlayer:Schedule not found for MTV - attempting to generate a one-day extention
2025-08-10 16:21:52,690 INFO:Liquid:Starting to build blocks for MTV
Traceback (most recent call last):
  File "/home/station/FieldStation42/fs42/station_player.py", line 279, in play_slot
    play_point = liquid.get_play_point(network_name, when)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/station/FieldStation42/fs42/liquid_manager.py", line 187, in get_play_point
    _block: LiquidBlock = self.get_programming_block(network_name, when)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/station/FieldStation42/fs42/liquid_manager.py", line 154, in get_programming_block
    raise ScheduleNotFound(f"Schedule doesn't exist for {network_name}")
fs42.liquid_manager.ScheduleNotFound: Schedule doesn't exist for MTV

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/station/FieldStation42/field_player.py", line 302, in <module>
    main_loop(trans_fn, shutdown_queue=shutdown_queue, api_proc=api_proc)
  File "/home/station/FieldStation42/field_player.py", line 129, in main_loop
    player_state = player.play_slot(
                   ^^^^^^^^^^^^^^^^^
  File "/home/station/FieldStation42/fs42/station_player.py", line 281, in play_slot
    self.schedule_panic(network_name)
  File "/home/station/FieldStation42/fs42/station_player.py", line 272, in schedule_panic
    schedule.add_days(1)
  File "/home/station/FieldStation42/fs42/liquid_schedule.py", line 238, in add_days
    self._increment("day")
  File "/home/station/FieldStation42/fs42/liquid_schedule.py", line 227, in _increment
    self._fluid(start_building, end_building)
  File "/home/station/FieldStation42/fs42/liquid_schedule.py", line 141, in _fluid
    clip_content = self.catalog.gather_clip_content(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/station/FieldStation42/fs42/catalog.py", line 481, in gather_clip_content
    current_duration += candidate.duration
                        ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'duration'
^C2025-08-10 16:22:07,603 CRITICAL:MainLoop:Received sig-int signal, attempting to exit gracefully...
2025-08-10 16:22:07,608 INFO:MainLoop:Shutdown completed as expected - exiting application
Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
  File "/home/station/FieldStation42/field_player.py", line 101, in sigint_handler
    exit(0)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 0

```

ETA: I see the missing schedules. I tried the ```--rebuild_catalog``` command, got the same "missing uvicorn" error message.

**Comment by shane-mason** [comment]
Try `pip3 install uvicorn` and see if that works. I'll check the installer, but you can also run it again and it should install any missing dependencies.

**Comment by ddrfr33k** [comment]
I had to reinstall both uvicorn and fastAPI. Station42.py is now rebuilding the catalog. I'll see if it launches after that.

**Comment by ddrfr33k** [comment]
Okay, Guide Channel appears now after rebuilding the catalog. However, I am still unable to change the channel. Still getting the same error message listed above when changing the channel.

**Comment by shane-mason** [comment]
Which error are you getting - both? Can you do this:

```
git pull
git status
````

And make sure that your repo is all up to date without any merge conflicts?

**Comment by ddrfr33k** [comment]
This is the weirdest thing. I left it unplugged for a week, fired it up, and now it's working again. I don't get it...

**Comment by shane-mason** [comment]
Everybody needs a break sometimes, even a pi :)
